
version: '3'
services:
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - my_network
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my_network
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
volumes:
  postgres: {}
networks:
  my_network:
    driver: bridge